# 域名转发规则配置
rules:
  - domainPattern: "google.com"
    forwardMethod: "proxy"
  - domainPattern: "services.googleapis.cn"
    forwardMethod: "proxy"
  - domainPattern: "*.cn"
    forwardMethod: "direct"
  - domainPattern: "*.douyu.com"
    forwardMethod: "direct"
  - domainPattern: "*.douyucdn.cn"
    forwardMethod: "direct"
  - domainPattern: "*.bilibili.com"
    forwardMethod: "direct"
  - domainPattern: "*.miui.com"
    forwardMethod: "direct"
  - domainPattern: "*.xiaomi.com"
    forwardMethod: "direct"
  - domainPattern: "*.zhihu.com"
    forwardMethod: "direct"
  - domainPattern: "*.zhimg.com"
    forwardMethod: "direct"
  - domainPattern: "*.hdslb.com"
    forwardMethod: "direct"
  - domainPattern: "*.biliapi.net"
    forwardMethod: "direct"
  - domainPattern: "*.alicdn.com"
    forwardMethod: "direct"
  - domainPattern: "*.alipay.com"
    forwardMethod: "direct"
  - domainPattern: "*.jd.com"
    forwardMethod: "direct"
  - domainPattern: "*.360buyimg.com"
    forwardMethod: "direct"
  - domainPattern: "*.feishu.cn"
    forwardMethod: "direct"
  - domainPattern: "*.feishucdn.com"
    forwardMethod: "direct"
  - domainPattern: "*.mi.com"
    forwardMethod: "direct"
  - domainPattern: "111.13.24.98"
    forwardMethod: "direct"
  - domainPattern: "*.qq.com"
    forwardMethod: "direct"
  - domainPattern: "*.edu.cn"
    forwardMethod: "direct"
  - domainPattern: "*.tianyancha.com"
    forwardMethod: "direct"
  - domainPattern: "*.taou.com"
    forwardMethod: "direct"
  - domainPattern: "*.bilivideo.com"
    forwardMethod: "direct"
  - domainPattern: "*.163.com"
    forwardMethod: "direct"
  - domainPattern: "download.zxcs.zip"
    forwardMethod: "direct"
  - domainPattern: "*.taobao.com"
    forwardMethod: "direct"
  - domainPattern: "*.zijieapi.com"
    forwardMethod: "direct"
  - domainPattern: "*.volces.com"
    forwardMethod: "direct"
  - domainPattern: "*.umeng.com"
    forwardMethod: "direct"
  - domainPattern: "*.deepseek.com"
    forwardMethod: "direct"
  - domainPattern: "*.fqnovelpic.com"
    forwardMethod: "direct"
  - domainPattern: "*.xiaomi.net"
    forwardMethod: "direct"
  - domainPattern: "*.xiaomixiaoai.com"
    forwardMethod: "direct"
  - domainPattern: "*.miwifi.com"
    forwardMethod: "direct"
  - domainPattern: "*.meituan.com"
    forwardMethod: "direct"
  - domainPattern: "*.meituan.net"
    forwardMethod: "direct"
  - domainPattern: "*.mijia.tech"
    forwardMethod: "direct"
  - domainPattern: "*.mijia.tech"
    forwardMethod: "direct"
  - domainPattern: "*.cainiao.com"
    forwardMethod: "direct"
  - domainPattern: "*.gitee.com"
    forwardMethod: "direct"
  - domainPattern: "*.aliyuncs.com"
    forwardMethod: "direct"    
  - domainPattern: "*.qcloud.com"
    forwardMethod: "direct"
  - domainPattern: "*.dianping.com"
    forwardMethod: "direct"
  - domainPattern: "*.smallparking.eu.org"
    forwardMethod: "direct"
  - domainPattern: "j1900"
    forwardMethod: "direct"
  - domainPattern: "*.smzdm.com"
    forwardMethod: "direct"
  - domainPattern: "*.myqcloud.com"
    forwardMethod: "direct"
  - domainPattern: "*.weixinbridge.com"
    forwardMethod: "direct"
  - domainPattern: "*.amap.com"
    forwardMethod: "direct"
  - domainPattern: "*.biligame.net"
    forwardMethod: "direct"
  - domainPattern: "*.biliapi.com"
    forwardMethod: "direct"
  - domainPattern: "*.aliyun.com"
    forwardMethod: "direct"
  - domainPattern: "*.alibaba.com"
    forwardMethod: "direct"
  - domainPattern: "*.alibabausercontent.com"
    forwardMethod: "direct"
  - domainPattern: "*.alipayobjects.com"
    forwardMethod: "direct"
  - domainPattern: "*.qichacha.com"
    forwardMethod: "direct"    
  - domainPattern: "*.qcc.com"
    forwardMethod: "direct"
  - domainPattern: "*.biligame.com"
    forwardMethod: "direct"   
  - domainPattern: "*.xyzcdn.net"
    forwardMethod: "direct"   
  - domainPattern: "*.xiaoyuzhoufm.com"
    forwardMethod: "direct"
  - domainPattern: "*.yuewen.com"
    forwardMethod: "direct"
  - domainPattern: "*.mi-img.com"
    forwardMethod: "direct"
  - domainPattern: "hm.baidu.com"
    forwardMethod: "block"
  - domainPattern: "*.baidu.com"
    forwardMethod: "block"    
  - domainPattern: "dash.cloudflare.com"
    forwardMethod: "direct"    
  - domainPattern: "*.douban.com"
    forwardMethod: "direct"
  - domainPattern: "*.doubanio.com"
    forwardMethod: "direct"    
  - domainPattern: "*.autonavi.com"
    forwardMethod: "direct"
  - domainPattern: "*.u-area.com"
    forwardMethod: "direct"
  - domainPattern: "*.wellcee.com"
    forwardMethod: "direct"
  - domainPattern: "*.ksord.com"
    forwardMethod: "direct"
  - domainPattern: "*.ksosoft.com"
    forwardMethod: "direct"
  - domainPattern: "*.xiaomiyoupin.com"
    forwardMethod: "direct"
  - domainPattern: "b23.tv"
    forwardMethod: "direct"
  - domainPattern: "*.geetest.com"
    forwardMethod: "direct"
  - domainPattern: "*.xoyo.com"
    forwardMethod: "direct"
  - domainPattern: "*.xoyocdn.com"
    forwardMethod: "direct"
  - domainPattern: "hls.yjjcfw.com"
    forwardMethod: "direct"
  - domainPattern: "play.sportsteam368.com"
    forwardMethod: "direct"
  - domainPattern: "*.netease.com"
    forwardMethod: "direct"
  - domainPattern: "my.oschina.net"
    forwardMethod: "direct"
  - domainPattern: "*.getui.com"
    forwardMethod: "block"
  - domainPattern: "*.gepush.com"
    forwardMethod: "block"
  - domainPattern: "*.igexin.com"
    forwardMethod: "block"
  - domainPattern: "*.getui.net"
    forwardMethod: "block"
  - domainPattern: "*.miguvideo.com"
    forwardMethod: "direct"
  - domainPattern: "*.fcbox.com"
    forwardMethod: "direct"    
  - domainPattern: "*.huya.com"
    forwardMethod: "direct"
  - domainPattern: "*.qidian.com"
    forwardMethod: "direct"
  - domainPattern: "*.digitalchina.com"
    forwardMethod: "direct"
  - domainPattern: "*.steamchina.com"
    forwardMethod: "direct"
  - domainPattern: "steamvideo-a.akamaihd.net"
    forwardMethod: "direct"
  - domainPattern: "steamuserimages-a.akamaihd.net"
    forwardMethod: "direct"
  - domainPattern: "steamusercontent-a.akamaihd.net"
    forwardMethod: "direct"
  - domainPattern: "steamstore-a.akamaihd.net"
    forwardMethod: "direct"
  - domainPattern: "steamcommunity-a.akamaihd.net"
    forwardMethod: "direct"
  - domainPattern: "steamcdn-a.akamaihd.net"
    forwardMethod: "direct"
  - domainPattern: "steambroadcast.akamaized.net"
    forwardMethod: "direct"
  - domainPattern: "xz.pphimalayanrt.com"
    forwardMethod: "direct"
  - domainPattern: "steamstatic.com.8686c.com"
    forwardMethod: "direct"
  - domainPattern: "steampowered.com.8686c.com"
    forwardMethod: "direct"
  - domainPattern: "steampipe.steamcontent.tnkjmec.com"
    forwardMethod: "direct"
  - domainPattern: "st.dl.pinyuncloud.com"
    forwardMethod: "direct"
  - domainPattern: "st.dl.eccdnx.com"
    forwardMethod: "direct"
  - domainPattern: "st.dl.bscstorage.net"
    forwardMethod: "direct"
  - domainPattern: "dl.steam.ksyna.com"
    forwardMethod: "direct"
  - domainPattern: "dl.steam.clngaa.com"
    forwardMethod: "direct"
  - domainPattern: "*.wmsj.cn"
    forwardMethod: "direct"
  - domainPattern: "wpad"
    forwardMethod: "block"
  - domainPattern: "tpstelemetry.tencent.com"
    forwardMethod: "block"
  - domainPattern: "stun.hitv.com"
    forwardMethod: "block"
  - domainPattern: "stun.chat.bilibili.com"
    forwardMethod: "block"
  - domainPattern: "hf-mirror.com"
    forwardMethod: "direct"
  - domainPattern: "*.alibabachengdun.com"
    forwardMethod: "direct"
  - domainPattern: "xget.xi-xu.me"
    forwardMethod: "direct"
  - domainPattern: "*.ele.me"
    forwardMethod: "direct" 
  - domainPattern: "*.qingcloud.com"
    forwardMethod: "direct"     
  - domainPattern: "*.tanx.com"
    forwardMethod: "direct"     
  - domainPattern: "*.mmstat.com"
    forwardMethod: "direct"     
  - domainPattern: "*.dingtalk.com"
    forwardMethod: "direct"
  - domainPattern: "*.linkease.com"
    forwardMethod: "direct"
  - domainPattern: "*.koolcenter.com"
    forwardMethod: "direct"
  - domainPattern: "*.mxhichina.com"
    forwardMethod: "direct"    
  - domainPattern: "*.bdstatic.com"
    forwardMethod: "direct"        
  - domainPattern: "*.126.net"
    forwardMethod: "direct"   
  - domainPattern: "*.volceapplog.com"
    forwardMethod: "direct"
  - domainPattern: "*.bcebos.com"
    forwardMethod: "block"
  - domainPattern: "*.pcbeta.com"
    forwardMethod: "direct"
  - domainPattern: "*.ksyun.com"
    forwardMethod: "direct"
  - domainPattern: "*.ctobsnssdk.com"
    forwardMethod: "direct"
  - domainPattern: "*.irs03.com"
    forwardMethod: "direct"
  - domainPattern: "*.bilicomic.com"
    forwardMethod: "direct"
  - domainPattern: "*.bilicomics.com"
    forwardMethod: "direct"
  - domainPattern: "*.wldmarket.com"
    forwardMethod: "direct"
  - domainPattern: "*.douyin.com"
    forwardMethod: "direct"
  - domainPattern: "*.pangolin-sdk-toutiao.com"
    forwardMethod: "direct"
  - domainPattern: "*.pglstatp-toutiao.com"
    forwardMethod: "direct"
  - domainPattern: "*.bytescm.com"
    forwardMethod: "direct"
  - domainPattern: "*.snssdk.com"
    forwardMethod: "direct"
  - domainPattern: "*.bytedance.com"
    forwardMethod: "direct"
  - domainPattern: "*.pangolin-sdk-toutiao1.com"
    forwardMethod: "direct"
  - domainPattern: "*.mintegral.net"
    forwardMethod: "direct"
  - domainPattern: "*.byteimg.com"
    forwardMethod: "direct"
  - domainPattern: "*.byteacctimg.com"
    forwardMethod: "direct"
  - domainPattern: "*.yhgfb-cn-static.com"
    forwardMethod: "direct"
  - domainPattern: "*.ibytedapm.com"
    forwardMethod: "direct"
  - domainPattern: "*.bytetcc.com"
    forwardMethod: "direct"
  - domainPattern: "*.byted-static.com"
    forwardMethod: "direct"
  - domainPattern: "*.cmpassport.com"
    forwardMethod: "direct"
  - domainPattern: "*.todesk.com"
    forwardMethod: "direct"
  - domainPattern: "*.sogou.com"
    forwardMethod: "direct"
  - domainPattern: "*.sogoucdn.com"
    forwardMethod: "direct"
  - domainPattern: "*.csdn.net"
    forwardMethod: "direct"
  - domainPattern: "*.openinstall.io"
    forwardMethod: "direct"
  - domainPattern: "*.pstatp.com"
    forwardMethod: "direct"
  - domainPattern: "*.openinstall.com"
    forwardMethod: "direct"
  - domainPattern: "*.npmmirror.com"
    forwardMethod: "direct"
  - domainPattern: "connectivity-check.ubuntu.com"
    forwardMethod: "direct"
  - domainPattern: "*.isjike.com"
    forwardMethod: "direct"
  - domainPattern: "*.51y5.net"
    forwardMethod: "direct"
  - domainPattern: "*.youdao.com"
    forwardMethod: "direct"
  - domainPattern: "*.wpsmail.net"
    forwardMethod: "direct"
  - domainPattern: "*.miaozhen.com"
    forwardMethod: "direct"
  - domainPattern: "*.jdpay.com"
    forwardMethod: "direct"
  - domainPattern: "*.300hu.com"
    forwardMethod: "direct"
  - domainPattern: "*.avlyun.com"
    forwardMethod: "direct"
  - domainPattern: "*.gdtimg.com"
    forwardMethod: "direct"
  - domainPattern: "*.sandai.net"
    forwardMethod: "direct"
  - domainPattern: "*.y5kfpt.com"
    forwardMethod: "direct"
  - domainPattern: "*.zztfly.com"
    forwardMethod: "direct"
  - domainPattern: "*.joying.com"
    forwardMethod: "direct"
  - domainPattern: "*.myhuaweicloud.com"
    forwardMethod: "direct"
  - domainPattern: "*.visualstudio.com"
    forwardMethod: "direct"
  - domainPattern: "*.xiaomimobile.com"
    forwardMethod: "direct"
  - domainPattern: "*.wavpub.com"
    forwardMethod: "direct"
  - domainPattern: "*.pddpic.com"
    forwardMethod: "direct"
  - domainPattern: "*.cpatrk.net"
    forwardMethod: "direct"
  - domainPattern: "*.clickwifi.net"
    forwardMethod: "direct"